#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'LucasBarreto'
        hostname: ubuntu-dev
        username: barreto
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - git
        - libreoffice
        - gimp
        - vlc
        - curl
        - wget
        - python3
        - python3-pip
        - openjdk-17-jdk
        - maven
        - gradle
        - wireshark
        - nmap
        - openvpn
        - htop
        - tmux
        - net-tools
        - steam
        - gnome-tweaks
        - gnome-shell-extensions
        - gaphor
    snaps:
        - name: spotify
          channel: stable
          classic: false
        - name: code
          channel: stable
          classic: true
        - name: postman
          channel: stable
          classic: true
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
