#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'LucasBarreto'
        hostname: ubuntu-dev
        username: barreto
        password: '123773'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - git
        - libreoffice
        - gimp
        - vlc
        - curl
        - wget
        - python3
        - python3-pip
        - openjdk-17-jdk
        - maven
        - gradle
        - wireshark
        - nmap
        - openvpn
        - htop
        - tmux
        - net-tools
        - steam
        - gnome-tweaks
        - gnome-shell-extensions
        - gaphor  # Software de modelagem UML
    snaps:
        - name: spotify
          channel: stable
          classic: false
        - name: code
          channel: stable
          classic: true
        - name: postman
          channel: stable
          classic: true
        - name: docker
          channel: stable
          classic: true
        - name: obs-studio
          channel: stable
          classic: true
        - name: eclipse
          channel: stable
          classic: true
        - name: ten-forward
          channel: latest/stable
          classic: true
        - name: mini-text
          channel: latest/stable
          classic: true
        - name: file-shredder
          channel: latest/stable
          classic: true
        - name: webapps
          channel: latest/stable
          classic: true
        - name: apostrophe
          channel: latest/stable
          classic: true
        - name: emblem
          channel: latest/stable
          classic: true
        - name: dev-toolbox
          channel: latest/stable
          classic: true
        - name: collision
          channel: latest/stable
          classic: true
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
