#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Lucas Barreto'
        hostname: ubuntu-dev
        username: barreto
        password: "$6$abc123$3vT1xD/fjOeU98kAq1kXYC7xi9mgqDO79u6oE2Q8h8PVNp6D1yW.lNkp0u3u3bUURdOsX.KdYz5dtJY0qU48f/"
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"

    packages:
        - git
        - curl
        - wget
        - build-essential
        - openjdk-17-jdk
        - gnome-tweaks
        - docker.io
        - docker-compose
        - nodejs
        - npm

    snaps:
        - name: code
          channel: stable
          classic: true
        - name: google-chrome
          channel: stable
        - name: steam
          channel: stable
          classic: true

    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
